// Theme Registry — 빌트인 테마 정의 + 조회
// SSOT: 모든 테마 정의는 이 파일에서만 관리

import { ThemeDefinition } from './types';

export const BUILT_IN_THEMES: ThemeDefinition[] = [
  {
    id: 'clean-white',
    name: '클린 화이트',
    description: '깔끔한 흰색 배경에 파란 액센트, 미니멀한 디자인',
    tone: '깔끔하고 신뢰감 있는 톤. 군더더기 없이 핵심만 전달하되 전문적인 느낌을 유지.',
    colors: {
      primary: '#2563EB',
      secondary: '#3B82F6',
      accent: '#2563EB',
      background: '#FFFFFF',
      surface: '#F8F7F4',
      surfaceAlt: '#F3F4F6',
      text: '#222222',
      textSub: '#666666',
      textMuted: '#999999',
      border: '#E5E7EB',
    },
    typography: {
      fontFamily: "'Pretendard', -apple-system, sans-serif",
      h1: '24px', h2: '18px', h3: '14px',
      body: '13px', small: '11px',
      lineHeight: '1.65',
      headingWeight: 600,
    },
    spacing: {
      sectionPadding: '28px 24px',
      itemGap: '12px',
      cardPadding: '14px',
    },
    decorations: {
      cardRadius: '8px',
      sectionRadius: '0',
      divider: 'line',
      badge: 'pill',
      shadow: 'none',
    },
    blockVariants: {
      hero: 'centered',
      feature: 'list',
      painpoint: 'bullets',
      solution: 'cards',
      review: 'cards',
      spec: 'table',
      faq: 'list',
      trust: 'row',
      howto: 'steps',
      cta: 'cards',
      compare: 'table',
    },
  },
  {
    id: 'modern-dark',
    name: '모던 다크',
    description: '어두운 배경에 밝은 텍스트, 세련된 느낌',
    tone: '세련되고 프리미엄한 톤. 짧고 임팩트 있는 문장으로 제품의 기술력과 디자인을 강조.',
    colors: {
      primary: '#60A5FA',
      secondary: '#818CF8',
      accent: '#A78BFA',
      background: '#0F172A',
      surface: '#1E293B',
      surfaceAlt: '#162032',
      text: '#F1F5F9',
      textSub: '#94A3B8',
      textMuted: '#64748B',
      border: '#334155',
    },
    typography: {
      fontFamily: "'Pretendard', -apple-system, sans-serif",
      h1: '26px', h2: '19px', h3: '14px',
      body: '13px', small: '11px',
      lineHeight: '1.6',
      headingWeight: 600,
    },
    spacing: {
      sectionPadding: '32px 24px',
      itemGap: '14px',
      cardPadding: '16px',
    },
    decorations: {
      cardRadius: '10px',
      sectionRadius: '0',
      divider: 'gradient',
      badge: 'pill',
      shadow: '0 2px 8px rgba(0,0,0,0.3)',
    },
    blockVariants: {
      hero: 'centered',
      feature: 'cards',
      painpoint: 'cards',
      solution: 'cards',
      review: 'quotes',
      spec: 'striped',
      faq: 'cards',
      trust: 'cards',
      howto: 'timeline',
      cta: 'highlight',
      compare: 'table',
    },
  },
  {
    id: 'natural-warm',
    name: '내추럴 웜',
    description: '따뜻한 크림 톤에 앰버 액센트, 자연스러운 느낌',
    tone: '따뜻하고 자연스러운 톤. 친근한 대화체로 제품의 감성적 가치를 전달. 과장 없이 진정성 있게.',
    colors: {
      primary: '#D97706',
      secondary: '#B45309',
      accent: '#F59E0B',
      background: '#FFFBEB',
      surface: '#FEF3C7',
      surfaceAlt: '#FFF7ED',
      text: '#451A03',
      textSub: '#78350F',
      textMuted: '#92400E',
      border: '#FDE68A',
    },
    typography: {
      fontFamily: "'Pretendard', -apple-system, sans-serif",
      h1: '24px', h2: '18px', h3: '14px',
      body: '14px', small: '12px',
      lineHeight: '1.7',
      headingWeight: 600,
    },
    spacing: {
      sectionPadding: '30px 24px',
      itemGap: '14px',
      cardPadding: '16px',
    },
    decorations: {
      cardRadius: '12px',
      sectionRadius: '0',
      divider: 'gradient',
      badge: 'pill',
      shadow: '0 1px 4px rgba(146,64,14,0.1)',
    },
    blockVariants: {
      hero: 'centered',
      feature: 'alternating',
      painpoint: 'bullets',
      solution: 'list',
      review: 'quotes',
      spec: 'table',
      faq: 'list',
      trust: 'row',
      howto: 'steps',
      cta: 'cards',
      compare: 'table',
    },
  },
  {
    id: 'premium-gold',
    name: '프리미엄 골드',
    description: '다크 배경에 골드 액센트, 고급스러운 느낌',
    tone: '고급스럽고 격조 있는 톤. 제품의 프리미엄 가치와 장인정신을 강조. 권위 있으면서도 세련된 표현.',
    colors: {
      primary: '#D4AF37',
      secondary: '#C9A838',
      accent: '#F5D060',
      background: '#0A0A0A',
      surface: '#1A1A1A',
      surfaceAlt: '#141414',
      text: '#F5F0E1',
      textSub: '#BFB49A',
      textMuted: '#8A7E68',
      border: '#2E2A20',
    },
    typography: {
      fontFamily: "'Pretendard', -apple-system, sans-serif",
      h1: '28px', h2: '20px', h3: '15px',
      body: '14px', small: '11px',
      lineHeight: '1.6',
      headingWeight: 500,
    },
    spacing: {
      sectionPadding: '36px 28px',
      itemGap: '16px',
      cardPadding: '20px',
    },
    decorations: {
      cardRadius: '4px',
      sectionRadius: '0',
      divider: 'gradient',
      badge: 'square',
      shadow: '0 2px 12px rgba(0,0,0,0.4)',
    },
    blockVariants: {
      hero: 'centered',
      feature: 'list',
      painpoint: 'cards',
      solution: 'cards',
      review: 'quotes',
      spec: 'striped',
      faq: 'cards',
      trust: 'cards',
      howto: 'timeline',
      cta: 'highlight',
      compare: 'table',
    },
  },
  {
    id: 'pop-vivid',
    name: '팝 컬러',
    description: '밝고 활기찬 색상, 큰 타이포, 에너지 넘치는 디자인',
    tone: '밝고 활기찬 톤. 젊고 트렌디한 느낌으로 제품의 재미와 활력을 강조. 이모지와 감탄사를 적극 활용.',
    colors: {
      primary: '#EC4899',
      secondary: '#8B5CF6',
      accent: '#06B6D4',
      background: '#FAFAFA',
      surface: '#FFF1F2',
      surfaceAlt: '#F0F9FF',
      text: '#18181B',
      textSub: '#52525B',
      textMuted: '#A1A1AA',
      border: '#E4E4E7',
    },
    typography: {
      fontFamily: "'Pretendard', -apple-system, sans-serif",
      h1: '28px', h2: '20px', h3: '15px',
      body: '14px', small: '12px',
      lineHeight: '1.6',
      headingWeight: 700,
    },
    spacing: {
      sectionPadding: '28px 24px',
      itemGap: '12px',
      cardPadding: '16px',
    },
    decorations: {
      cardRadius: '16px',
      sectionRadius: '0',
      divider: 'none',
      badge: 'pill',
      shadow: '0 4px 14px rgba(0,0,0,0.08)',
    },
    blockVariants: {
      hero: 'left',
      feature: 'cards',
      painpoint: 'cards',
      solution: 'cards',
      review: 'cards',
      spec: 'table',
      faq: 'cards',
      trust: 'row',
      howto: 'steps',
      cta: 'highlight',
      compare: 'cards',
    },
  },
];

// === 조회 함수 ===

export function getThemeById(id: string): ThemeDefinition | null {
  return BUILT_IN_THEMES.find(t => t.id === id) || null;
}

export function getDefaultTheme(): ThemeDefinition {
  return BUILT_IN_THEMES[0]; // clean-white
}

export function listThemes(): { id: string; name: string; description: string }[] {
  return BUILT_IN_THEMES.map(t => ({ id: t.id, name: t.name, description: t.description }));
}
